default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>

development: *default
test: *default
staging: *default
production: *default
