SAMPLE_LTI_REQUEST = {
  "oauth_version"=>"1.0",
  # "oauth_nonce"=>"SOME_NONCE_VALUE",
  # "oauth_timestamp"=>"1478277786",
  # "oauth_consumer_key"=>"CONSUMER_KEY_VALUE",
  "resource_link_title"=>"Transversions",
  "resource_link_description"=>"",
  "user_id"=>"65432",
  "lis_person_sourcedid"=>"123456",
  "roles"=>"Instructor",
  "context_id"=>"98989",
  "context_label"=>"ANTH-290-01: Anthro of Digital Cultures-201602",
  "context_title"=>"ANTH-290-01: Anthro of Digital Cultures-201602",
  "resource_link_id"=>"384",
  "context_type"=>"CourseSection",
  "lis_course_section_sourcedid"=>"21050.201602",
  "lis_result_sourcedid"=>"STRING_ENCODED_JSON",
  "lis_outcome_service_url"=>"https://cms.whittier.edu/mod/lti/service.php",
  "lis_person_name_given"=>"Eli",
  "lis_person_name_family"=>"Thorkelson",
  "lis_person_name_full"=>"Eli Thorkelson",
  "ext_user_username"=>"ethorkel",
  "lis_person_contact_email_primary"=>"ethorkel@whittier.edu",
  "launch_presentation_locale"=>"en_us",
  "ext_lms"=>"moodle-2",
  "tool_consumer_info_product_family_code"=>"moodle",
  "tool_consumer_info_version"=>"2015051107",
  "oauth_callback"=>"about:blank",
  "lti_version"=>"LTI-1p0",
  "lti_message_type"=>"basic-lti-launch-request",
  "tool_consumer_instance_guid"=>"cms.whittier.edu",
  "tool_consumer_instance_name"=>"Whittier College Moodle",
  "launch_presentation_document_target"=>"frame",
  "launch_presentation_return_url"=>"https://cms.whittier.edu/mod/lti/return.php?course=98989&launch_container=5&instanceid=384&sesskey=x1Cu4SUnnf",
  "oauth_signature_method"=>"HMAC-SHA1",
  # "oauth_signature"=>"MUdq0bt+DUUHsqeS0MRVF1vsIsQ="
}
